### ISSUE TITLE
AppSettingsPlugin.swift:5:43, Attribute can only be applied to declarations, not types

### ISSUE THREAD

**Issue by yakup2525** [spencerccf/app_settings#232]
Attribute can only be applied to declarations, not types  error after package update 

Failed to build iOS app
Swift Compiler Error (Xcode): Attribute can only be applied to declarations, not types

.pub-cache/hosted/pub.dev/app_settings-5.2.0/ios/app_settings/sources/app_settings/AppSettingsPlugin.swift:5:43
AppSettingsPlugin.swift:5

Could not build the application for the simulator.
Error launching application on iPhone 15.

**Comment by MrRongoose** [comment]
Same issue here. Following

**Comment by 1encore** [comment]
Same here, happens on 5.2.0, downgraded to 5.1.1

**Comment by VB10** [comment]
that works for me thank you @yakup2525 . Anyone can use directly this:

``` yaml
  app_settings:
    git:
      url: https://github.com/yakup2525/app_settings
      ref: master
```
